/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load() {
    dashcode.setupParts();
}

function makeResultVisible(id) {
   document.getElementById("resultBox").style.visibility = "visible";

   if (id == "box1") {
    document.getElementById("box1").style.opacity = 1;
    document.getElementById("box2").style.opacity = 0.5;
    document.getElementById("box3").style.opacity = 0.5;
    document.getElementById("box4").style.opacity = 0.5;
   } else if (id == "box2") {
    document.getElementById("box2").style.opacity = 1;
    document.getElementById("box1").style.opacity = 0.5;
    document.getElementById("box3").style.opacity = 0.5;
    document.getElementById("box4").style.opacity = 0.5;
   } else if (id == "box3") {
    document.getElementById("box3").style.opacity = 1;
    document.getElementById("box1").style.opacity = 0.5;
    document.getElementById("box2").style.opacity = 0.5;
    document.getElementById("box4").style.opacity = 0.5;
   } else {
    document.getElementById("box4").style.opacity = 1;
    document.getElementById("box1").style.opacity = 0.5;
    document.getElementById("box2").style.opacity = 0.5;
    document.getElementById("box3").style.opacity = 0.5;
    //move('4');
   }
}

  

function move(n) {
  var elem = document.getElementById("myBar");   
  var width = 0;
  var id = setInterval(frame, 5000);
  function frame() {
        if (width >= n*5) {
      clearInterval(id);
    } else {
      width=width+5; 
      elem.style.width = width + '%'; 
      document.getElementById("label").innerHTML = width * 1  + '%';
    }
  }
  location.reload();
}